#!/bin/bash

[ "$#" != "3" ] || { echo "Usage: $(basename "$0") filename_of_image busybox_dir"; exit 1; }

CWD=$(pwd)
BUSYBOX=$2
TMPDIR=rootfs
mkdir -p $TMPDIR
dd if=/dev/zero of=rootfs.img bs=1M count=32
mkfs.ext3 rootfs.img
mount -o loop rootfs.img $TMPDIR
cd  $TMPDIR
mkdir -p dev/pts etc/init.d mnt proc root sys tmp usr/local
chmod a+rwxt tmp

cd ${CWD}
cp -rf ${BUSYBOX}/_install/* $TMPDIR
cp -rf app/bin/* $TMPDIR/bin
cp -rf app/workspace $TMPDIR
cp -rf app/pkg/* $TMPDIR/usr/local
cd  $TMPDIR
mkdir -p usr/share/udhcpc
#cp -rf ${BUSYBOX}/examples/udhcp/simple.script  $TMPDIR/usr/share/udhcpc/default.script

cat << EOF > etc/profile
echo
echo "Let's hack the kernel! keloyang"
echo
EOF

cat << EOF > etc/fstab
proc  /proc  proc  defaults  0  0
sysfs  /sys  sysfs defaults  0  0
tmpfs  /tmp  tmpfs defaults  0  0
EOF

cat << EOF > etc/inittab
::sysinit:/etc/init.d/rcS
::respawn:-/bin/sh
tty2::askfirst:-/bin/sh
::ctrlaltdel:/bin/umount -a -r
EOF

cat << EOF > etc/init.d/rcS
#!bin/sh
/bin/mount -a
/sbin/mdev -s
mkdir /dev/pts
mount -vt devpts devpts /dev/pts
#/sbin/ifconfig eth0 up >/dev/null 2>&1 && /sbin/udhcpc eth0 >/dev/null 2>&1
ifconfig lo up
ifconfig eth0 up
ifconfig eth0 172.20.0.10 netmask 255.255.255.0
route add default gw 172.20.0.1

/usr/local/sshdog/start.sh
EOF

cat << EOF > etc/resolv.conf
nameserver 192.168.1.1
EOF

chmod 755 etc/init.d/rcS

#find ./ | cpio -o -H newc | gzip > ${CWD}/${1}
cd ${CWD}
umount $TMPDIR
rm -rf $TMPDIR

echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A POSTROUTING -o eth0 -s 172.20.0.0/24 -j MASQUERADE

cat << EOF > /etc/qemu-ifup
#!/bin/bash
ifconfig "\$1" 172.20.0.1
EOF

exit 0
